### ISSUE TITLE
关于copy的一个小问题

### ISSUE THREAD

**Issue by huangchunzhen** [LearningOS/rcore_step_by_step#15]

**Comment by wangrunji0408** [comment]
`Copy` 的角色更类似于 **标记(marker)**（类比 `Send`, `Sync`）。它的语义是：类型可以**按位复制**。

举个例子：引用计数 `Arc` 就是 `Clone` 而不是 `Copy`，因为每次复制对象都需要增加计数，不能简单地复制指针内容。

`Copy` 本质上是对 `Clone` 行为的进一步约束，没有自己单独的行为，也就无从谈及**重载**了。
