### ISSUE TITLE
关于ex15

### ISSUE THREAD

**Issue by juanhair** [LearningOS/rcore_step_by_step#16]
rust中是否有支持指针类型转换的方法，类似c语言中的char* 强制转换成int *。

**Comment by wangrunji0408** [comment]
```rust
let mut c = b'x';
let p1 = &mut c as *mut u8;
let p2 = p1 as *mut i32;
```
参考：[Rust 程序设计语言](https://kaisery.github.io/trpl-zh-cn/ch19-01-unsafe-rust.html#a解引用裸指针)
