### ISSUE TITLE
How about using opensbi to replace out-of-date bbl.

### ISSUE THREAD

**Issue by sequencer** [LearningOS/rcore_step_by_step#5]
bbl and pk is deprecated for RISC-V currently.
https://github.com/riscv/opensbi is the replacement of bbl. It is more clean and portable for baremetal software.
Any idea for porting bbl to opensbi?

**Comment by wangrunji0408** [comment]
Hi.

The upstream [rCore](https://github.com/rcore-os/rCore) project has replaced bbl by OpenSBI 3 weeks ago. 
But the step-by-step project does not follow up in time and we will update it soon.

I noticed your issue at rust-embedded/wg just now. 
Currently, we have to setup page table and enable paging before going to Rust code.
I have written a demo about how to write a minimal program with OpenSBI in Rust: [rust-rv64-kernel](https://github.com/wangrunji0408/rust-rv64-kernel)
Hope it helps.

**Comment by sequencer** [comment]
Oh that helps me a lot!
Thank you!

**Comment by xy-plus** [comment]
Hello, I already used opensbi replace bbl recently. Our repo seems pure Rust now!
