### ISSUE TITLE
周进展纪要（7.7-7.12）

### ISSUE THREAD

**Issue by chyyuu** [LearningOS/rcore_step_by_step#7]
陈渝：
组织TA，安排TA与学生的对接，准备rcore实验，具体内容如下：
https://github.com/LearningOS/rcore_step_by_step/wiki/rCore-Summer-of-Code

本周离开的学生：赵龙飞，陈鸿基

**Comment by chyyuu** [comment]
吴超

**Comment by juanhair** [comment]
参照rcore课程准备https://github.com/rcore-os/rCore/wiki/tutorial， 在“Rust 程序设计语言 简体中文版”中自学rust编程语言，具体内容如下：
https://kaisery.github.io/trpl-zh-cn/ch05-02-example-structs.html
并且在“通过例子学Rust”中按照对应章节的内容进行编程实例练习， 具体内容如下：
https://rustwiki.org/zh-CN/rust-by-example/flow_control/while_let.html
目前学习进度为，“Rust程序设计语言 简体中文版”学习至第9章错误处理，“笨办法学C语言”练习至第10题，GitHub repo链接为https://github.com/juanhair/-Rust-。

**Comment by coolbacon** [comment]
参照rcore课程准备https://github.com/rcore-os/rCore/wiki/tutorial， 在“Rust 程序设计语言 简体中文版”中自学rust编程语言，并且在“通过例子学Rust”中按照对应章节的内容进行编程实例练习。目前进度第三章，练习已上传。地址是：https://github.com/coolbacon/homework.git

**Comment by ruoruo1999** [comment]
目前因为工作原因并未及时开始学习，预计于明日开始学习本周的任务在下周提交作业的时候一并提交，对于未及时开展学习我深表歉意并会努力跟上。

**Comment by huangchunzhen** [comment]
参照rcore课程准备https://github.com/rcore-os/rCore/wiki/tutorial， 辅以阅读《计算机系统》，在“Rust 程序设计语言 简体中文版”中自学rust编程语言，同时阅读《Rust编程之道》辅以理解。并且在“通过例子学Rust”中按照对应章节的内容进行编程实例练习。目前学习进度为，“Rust程序设计语言 简体中文版”学习至第8章常见集合，“通过例子学Rust”已跟随代码学习至第5章类型系统（3.2之前习题已全部提交）。
<ruby the hard way>已练习至第8章。Github Repo链接为https://github.com/huangchunzhen/Rust_OS_learning_Tsinghua/tree/Project2

**Comment by Yourens** [comment]
Rust book 看到第十章。 笨办法学python 用rust 实现 练习到第8个。
https://github.com/Yourens/rustexam

**Comment by zhenyanjie** [comment]
目前因为暑期实习原因并未及时开始学习，下周争取补上。

**Comment by hpfsxfy** [comment]
参照rcore课程准备https://github.com/rcore-os/rCore/wiki/tutorial， 在“Rust 程序设计语言 简体中文版”中自学rust编程语言，并且在“通过例子学Rust”中按照对应章节的内容进行编程实例练习。目前学习至第三章，练习上传地址是：https://github.com/hpfsxfy/homework
